// Code generated by MockGen. DO NOT EDIT.
// Source: runclub/internal/domain/repository (interfaces: TemplateRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_template.go -package=mocks runclub/internal/domain/repository TemplateRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entity "runclub/internal/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockTemplateRepository is a mock of TemplateRepository interface.
type MockTemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateRepositoryMockRecorder
	isgomock struct{}
}

// MockTemplateRepositoryMockRecorder is the mock recorder for MockTemplateRepository.
type MockTemplateRepositoryMockRecorder struct {
	mock *MockTemplateRepository
}

// NewMockTemplateRepository creates a new mock instance.
func NewMockTemplateRepository(ctrl *gomock.Controller) *MockTemplateRepository {
	mock := &MockTemplateRepository{ctrl: ctrl}
	mock.recorder = &MockTemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateRepository) EXPECT() *MockTemplateRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTemplateRepository) Create(ctx context.Context, tmpl *entity.Template) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tmpl)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTemplateRepositoryMockRecorder) Create(ctx, tmpl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTemplateRepository)(nil).Create), ctx, tmpl)
}

// Delete mocks base method.
func (m *MockTemplateRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTemplateRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTemplateRepository)(nil).Delete), ctx, id)
}

// GetByClubAndType mocks base method.
func (m *MockTemplateRepository) GetByClubAndType(ctx context.Context, clubID int64, tmplType entity.TemplateType) (*entity.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByClubAndType", ctx, clubID, tmplType)
	ret0, _ := ret[0].(*entity.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByClubAndType indicates an expected call of GetByClubAndType.
func (mr *MockTemplateRepositoryMockRecorder) GetByClubAndType(ctx, clubID, tmplType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByClubAndType", reflect.TypeOf((*MockTemplateRepository)(nil).GetByClubAndType), ctx, clubID, tmplType)
}

// GetByID mocks base method.
func (m *MockTemplateRepository) GetByID(ctx context.Context, id int64) (*entity.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTemplateRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTemplateRepository)(nil).GetByID), ctx, id)
}

// ListByClub mocks base method.
func (m *MockTemplateRepository) ListByClub(ctx context.Context, clubID int64) ([]entity.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByClub", ctx, clubID)
	ret0, _ := ret[0].([]entity.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByClub indicates an expected call of ListByClub.
func (mr *MockTemplateRepositoryMockRecorder) ListByClub(ctx, clubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByClub", reflect.TypeOf((*MockTemplateRepository)(nil).ListByClub), ctx, clubID)
}

// Update mocks base method.
func (m *MockTemplateRepository) Update(ctx context.Context, tmpl *entity.Template) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tmpl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTemplateRepositoryMockRecorder) Update(ctx, tmpl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTemplateRepository)(nil).Update), ctx, tmpl)
}
