// Code generated by MockGen. DO NOT EDIT.
// Source: runclub/internal/domain/repository (interfaces: ClubRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_club.go -package=mocks runclub/internal/domain/repository ClubRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entity "runclub/internal/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockClubRepository is a mock of ClubRepository interface.
type MockClubRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClubRepositoryMockRecorder
	isgomock struct{}
}

// MockClubRepositoryMockRecorder is the mock recorder for MockClubRepository.
type MockClubRepositoryMockRecorder struct {
	mock *MockClubRepository
}

// NewMockClubRepository creates a new mock instance.
func NewMockClubRepository(ctrl *gomock.Controller) *MockClubRepository {
	mock := &MockClubRepository{ctrl: ctrl}
	mock.recorder = &MockClubRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClubRepository) EXPECT() *MockClubRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClubRepository) Create(ctx context.Context, club *entity.Club) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, club)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClubRepositoryMockRecorder) Create(ctx, club any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClubRepository)(nil).Create), ctx, club)
}

// Delete mocks base method.
func (m *MockClubRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClubRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClubRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockClubRepository) GetByID(ctx context.Context, id int64) (*entity.Club, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Club)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockClubRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockClubRepository)(nil).GetByID), ctx, id)
}

// GetByTelegramChatID mocks base method.
func (m *MockClubRepository) GetByTelegramChatID(ctx context.Context, chatID int64) (*entity.Club, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTelegramChatID", ctx, chatID)
	ret0, _ := ret[0].(*entity.Club)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTelegramChatID indicates an expected call of GetByTelegramChatID.
func (mr *MockClubRepositoryMockRecorder) GetByTelegramChatID(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTelegramChatID", reflect.TypeOf((*MockClubRepository)(nil).GetByTelegramChatID), ctx, chatID)
}

// List mocks base method.
func (m *MockClubRepository) List(ctx context.Context) ([]entity.Club, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.Club)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClubRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClubRepository)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockClubRepository) Update(ctx context.Context, club *entity.Club) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, club)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockClubRepositoryMockRecorder) Update(ctx, club any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClubRepository)(nil).Update), ctx, club)
}
