// Code generated by MockGen. DO NOT EDIT.
// Source: runclub/internal/domain/repository (interfaces: RaceRepository,RaceRegistrationRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_race.go -package=mocks runclub/internal/domain/repository RaceRepository,RaceRegistrationRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entity "runclub/internal/domain/entity"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRaceRepository is a mock of RaceRepository interface.
type MockRaceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRaceRepositoryMockRecorder
	isgomock struct{}
}

// MockRaceRepositoryMockRecorder is the mock recorder for MockRaceRepository.
type MockRaceRepositoryMockRecorder struct {
	mock *MockRaceRepository
}

// NewMockRaceRepository creates a new mock instance.
func NewMockRaceRepository(ctrl *gomock.Controller) *MockRaceRepository {
	mock := &MockRaceRepository{ctrl: ctrl}
	mock.recorder = &MockRaceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRaceRepository) EXPECT() *MockRaceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRaceRepository) Create(ctx context.Context, race *entity.Race) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, race)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRaceRepositoryMockRecorder) Create(ctx, race any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRaceRepository)(nil).Create), ctx, race)
}

// Delete mocks base method.
func (m *MockRaceRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRaceRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRaceRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockRaceRepository) GetByID(ctx context.Context, id int64) (*entity.Race, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Race)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRaceRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRaceRepository)(nil).GetByID), ctx, id)
}

// ListByClub mocks base method.
func (m *MockRaceRepository) ListByClub(ctx context.Context, clubID int64) ([]entity.Race, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByClub", ctx, clubID)
	ret0, _ := ret[0].([]entity.Race)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByClub indicates an expected call of ListByClub.
func (mr *MockRaceRepositoryMockRecorder) ListByClub(ctx, clubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByClub", reflect.TypeOf((*MockRaceRepository)(nil).ListByClub), ctx, clubID)
}

// ListUpcomingByClub mocks base method.
func (m *MockRaceRepository) ListUpcomingByClub(ctx context.Context, clubID int64, from, to time.Time) ([]entity.Race, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUpcomingByClub", ctx, clubID, from, to)
	ret0, _ := ret[0].([]entity.Race)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUpcomingByClub indicates an expected call of ListUpcomingByClub.
func (mr *MockRaceRepositoryMockRecorder) ListUpcomingByClub(ctx, clubID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUpcomingByClub", reflect.TypeOf((*MockRaceRepository)(nil).ListUpcomingByClub), ctx, clubID, from, to)
}

// Update mocks base method.
func (m *MockRaceRepository) Update(ctx context.Context, race *entity.Race) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, race)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRaceRepositoryMockRecorder) Update(ctx, race any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRaceRepository)(nil).Update), ctx, race)
}

// MockRaceRegistrationRepository is a mock of RaceRegistrationRepository interface.
type MockRaceRegistrationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRaceRegistrationRepositoryMockRecorder
	isgomock struct{}
}

// MockRaceRegistrationRepositoryMockRecorder is the mock recorder for MockRaceRegistrationRepository.
type MockRaceRegistrationRepositoryMockRecorder struct {
	mock *MockRaceRegistrationRepository
}

// NewMockRaceRegistrationRepository creates a new mock instance.
func NewMockRaceRegistrationRepository(ctrl *gomock.Controller) *MockRaceRegistrationRepository {
	mock := &MockRaceRegistrationRepository{ctrl: ctrl}
	mock.recorder = &MockRaceRegistrationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRaceRegistrationRepository) EXPECT() *MockRaceRegistrationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRaceRegistrationRepository) Create(ctx context.Context, reg *entity.RaceRegistration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, reg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRaceRegistrationRepositoryMockRecorder) Create(ctx, reg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRaceRegistrationRepository)(nil).Create), ctx, reg)
}

// Delete mocks base method.
func (m *MockRaceRegistrationRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRaceRegistrationRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRaceRegistrationRepository)(nil).Delete), ctx, id)
}

// GetByRaceAndMember mocks base method.
func (m *MockRaceRegistrationRepository) GetByRaceAndMember(ctx context.Context, raceID, memberID int64) (*entity.RaceRegistration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRaceAndMember", ctx, raceID, memberID)
	ret0, _ := ret[0].(*entity.RaceRegistration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRaceAndMember indicates an expected call of GetByRaceAndMember.
func (mr *MockRaceRegistrationRepositoryMockRecorder) GetByRaceAndMember(ctx, raceID, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRaceAndMember", reflect.TypeOf((*MockRaceRegistrationRepository)(nil).GetByRaceAndMember), ctx, raceID, memberID)
}

// ListByMember mocks base method.
func (m *MockRaceRegistrationRepository) ListByMember(ctx context.Context, memberID int64) ([]entity.RaceRegistration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMember", ctx, memberID)
	ret0, _ := ret[0].([]entity.RaceRegistration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByMember indicates an expected call of ListByMember.
func (mr *MockRaceRegistrationRepositoryMockRecorder) ListByMember(ctx, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMember", reflect.TypeOf((*MockRaceRegistrationRepository)(nil).ListByMember), ctx, memberID)
}

// ListByRace mocks base method.
func (m *MockRaceRegistrationRepository) ListByRace(ctx context.Context, raceID int64) ([]entity.RaceRegistration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByRace", ctx, raceID)
	ret0, _ := ret[0].([]entity.RaceRegistration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByRace indicates an expected call of ListByRace.
func (mr *MockRaceRegistrationRepositoryMockRecorder) ListByRace(ctx, raceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByRace", reflect.TypeOf((*MockRaceRegistrationRepository)(nil).ListByRace), ctx, raceID)
}
