// Code generated by MockGen. DO NOT EDIT.
// Source: runclub/internal/domain/repository (interfaces: BotStateRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_botstate.go -package=mocks runclub/internal/domain/repository BotStateRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entity "runclub/internal/domain/entity"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockBotStateRepository is a mock of BotStateRepository interface.
type MockBotStateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBotStateRepositoryMockRecorder
	isgomock struct{}
}

// MockBotStateRepositoryMockRecorder is the mock recorder for MockBotStateRepository.
type MockBotStateRepositoryMockRecorder struct {
	mock *MockBotStateRepository
}

// NewMockBotStateRepository creates a new mock instance.
func NewMockBotStateRepository(ctrl *gomock.Controller) *MockBotStateRepository {
	mock := &MockBotStateRepository{ctrl: ctrl}
	mock.recorder = &MockBotStateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBotStateRepository) EXPECT() *MockBotStateRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBotStateRepository) Create(ctx context.Context, state *entity.BotState) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, state)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBotStateRepositoryMockRecorder) Create(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBotStateRepository)(nil).Create), ctx, state)
}

// Delete mocks base method.
func (m *MockBotStateRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBotStateRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBotStateRepository)(nil).Delete), ctx, id)
}

// DeleteOlderThan mocks base method.
func (m *MockBotStateRepository) DeleteOlderThan(ctx context.Context, before time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOlderThan", ctx, before)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOlderThan indicates an expected call of DeleteOlderThan.
func (mr *MockBotStateRepositoryMockRecorder) DeleteOlderThan(ctx, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOlderThan", reflect.TypeOf((*MockBotStateRepository)(nil).DeleteOlderThan), ctx, before)
}

// GetByTelegramAndFlow mocks base method.
func (m *MockBotStateRepository) GetByTelegramAndFlow(ctx context.Context, telegramID, chatID int64, flow entity.BotFlowType) (*entity.BotState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTelegramAndFlow", ctx, telegramID, chatID, flow)
	ret0, _ := ret[0].(*entity.BotState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTelegramAndFlow indicates an expected call of GetByTelegramAndFlow.
func (mr *MockBotStateRepositoryMockRecorder) GetByTelegramAndFlow(ctx, telegramID, chatID, flow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTelegramAndFlow", reflect.TypeOf((*MockBotStateRepository)(nil).GetByTelegramAndFlow), ctx, telegramID, chatID, flow)
}

// Update mocks base method.
func (m *MockBotStateRepository) Update(ctx context.Context, state *entity.BotState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBotStateRepositoryMockRecorder) Update(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBotStateRepository)(nil).Update), ctx, state)
}
