// Code generated by MockGen. DO NOT EDIT.
// Source: runclub/internal/domain/repository (interfaces: TrainingRepository,TrainingTrainerRepository,TrainingParticipantRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_training.go -package=mocks runclub/internal/domain/repository TrainingRepository,TrainingTrainerRepository,TrainingParticipantRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entity "runclub/internal/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockTrainingRepository is a mock of TrainingRepository interface.
type MockTrainingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTrainingRepositoryMockRecorder
	isgomock struct{}
}

// MockTrainingRepositoryMockRecorder is the mock recorder for MockTrainingRepository.
type MockTrainingRepositoryMockRecorder struct {
	mock *MockTrainingRepository
}

// NewMockTrainingRepository creates a new mock instance.
func NewMockTrainingRepository(ctrl *gomock.Controller) *MockTrainingRepository {
	mock := &MockTrainingRepository{ctrl: ctrl}
	mock.recorder = &MockTrainingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrainingRepository) EXPECT() *MockTrainingRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTrainingRepository) Create(ctx context.Context, training *entity.Training) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, training)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTrainingRepositoryMockRecorder) Create(ctx, training any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTrainingRepository)(nil).Create), ctx, training)
}

// Delete mocks base method.
func (m *MockTrainingRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTrainingRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTrainingRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockTrainingRepository) GetByID(ctx context.Context, id int64) (*entity.Training, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Training)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTrainingRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTrainingRepository)(nil).GetByID), ctx, id)
}

// ListByClub mocks base method.
func (m *MockTrainingRepository) ListByClub(ctx context.Context, clubID int64) ([]entity.Training, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByClub", ctx, clubID)
	ret0, _ := ret[0].([]entity.Training)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByClub indicates an expected call of ListByClub.
func (mr *MockTrainingRepositoryMockRecorder) ListByClub(ctx, clubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByClub", reflect.TypeOf((*MockTrainingRepository)(nil).ListByClub), ctx, clubID)
}

// ListByStatus mocks base method.
func (m *MockTrainingRepository) ListByStatus(ctx context.Context, status entity.TrainingStatus) ([]entity.Training, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStatus", ctx, status)
	ret0, _ := ret[0].([]entity.Training)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByStatus indicates an expected call of ListByStatus.
func (mr *MockTrainingRepositoryMockRecorder) ListByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStatus", reflect.TypeOf((*MockTrainingRepository)(nil).ListByStatus), ctx, status)
}

// Update mocks base method.
func (m *MockTrainingRepository) Update(ctx context.Context, training *entity.Training) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, training)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTrainingRepositoryMockRecorder) Update(ctx, training any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTrainingRepository)(nil).Update), ctx, training)
}

// MockTrainingTrainerRepository is a mock of TrainingTrainerRepository interface.
type MockTrainingTrainerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTrainingTrainerRepositoryMockRecorder
	isgomock struct{}
}

// MockTrainingTrainerRepositoryMockRecorder is the mock recorder for MockTrainingTrainerRepository.
type MockTrainingTrainerRepositoryMockRecorder struct {
	mock *MockTrainingTrainerRepository
}

// NewMockTrainingTrainerRepository creates a new mock instance.
func NewMockTrainingTrainerRepository(ctrl *gomock.Controller) *MockTrainingTrainerRepository {
	mock := &MockTrainingTrainerRepository{ctrl: ctrl}
	mock.recorder = &MockTrainingTrainerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrainingTrainerRepository) EXPECT() *MockTrainingTrainerRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTrainingTrainerRepository) Create(ctx context.Context, tt *entity.TrainingTrainer) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tt)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTrainingTrainerRepositoryMockRecorder) Create(ctx, tt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTrainingTrainerRepository)(nil).Create), ctx, tt)
}

// DeleteByTraining mocks base method.
func (m *MockTrainingTrainerRepository) DeleteByTraining(ctx context.Context, trainingID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByTraining", ctx, trainingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByTraining indicates an expected call of DeleteByTraining.
func (mr *MockTrainingTrainerRepositoryMockRecorder) DeleteByTraining(ctx, trainingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByTraining", reflect.TypeOf((*MockTrainingTrainerRepository)(nil).DeleteByTraining), ctx, trainingID)
}

// ListByTraining mocks base method.
func (m *MockTrainingTrainerRepository) ListByTraining(ctx context.Context, trainingID int64) ([]entity.TrainingTrainer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTraining", ctx, trainingID)
	ret0, _ := ret[0].([]entity.TrainingTrainer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTraining indicates an expected call of ListByTraining.
func (mr *MockTrainingTrainerRepositoryMockRecorder) ListByTraining(ctx, trainingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTraining", reflect.TypeOf((*MockTrainingTrainerRepository)(nil).ListByTraining), ctx, trainingID)
}

// MockTrainingParticipantRepository is a mock of TrainingParticipantRepository interface.
type MockTrainingParticipantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTrainingParticipantRepositoryMockRecorder
	isgomock struct{}
}

// MockTrainingParticipantRepositoryMockRecorder is the mock recorder for MockTrainingParticipantRepository.
type MockTrainingParticipantRepositoryMockRecorder struct {
	mock *MockTrainingParticipantRepository
}

// NewMockTrainingParticipantRepository creates a new mock instance.
func NewMockTrainingParticipantRepository(ctrl *gomock.Controller) *MockTrainingParticipantRepository {
	mock := &MockTrainingParticipantRepository{ctrl: ctrl}
	mock.recorder = &MockTrainingParticipantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrainingParticipantRepository) EXPECT() *MockTrainingParticipantRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTrainingParticipantRepository) Create(ctx context.Context, tp *entity.TrainingParticipant) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tp)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTrainingParticipantRepositoryMockRecorder) Create(ctx, tp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTrainingParticipantRepository)(nil).Create), ctx, tp)
}

// Delete mocks base method.
func (m *MockTrainingParticipantRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTrainingParticipantRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTrainingParticipantRepository)(nil).Delete), ctx, id)
}

// GetByTrainingAndMember mocks base method.
func (m *MockTrainingParticipantRepository) GetByTrainingAndMember(ctx context.Context, trainingID, memberID int64) (*entity.TrainingParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTrainingAndMember", ctx, trainingID, memberID)
	ret0, _ := ret[0].(*entity.TrainingParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTrainingAndMember indicates an expected call of GetByTrainingAndMember.
func (mr *MockTrainingParticipantRepositoryMockRecorder) GetByTrainingAndMember(ctx, trainingID, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTrainingAndMember", reflect.TypeOf((*MockTrainingParticipantRepository)(nil).GetByTrainingAndMember), ctx, trainingID, memberID)
}

// ListByTraining mocks base method.
func (m *MockTrainingParticipantRepository) ListByTraining(ctx context.Context, trainingID int64) ([]entity.TrainingParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTraining", ctx, trainingID)
	ret0, _ := ret[0].([]entity.TrainingParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTraining indicates an expected call of ListByTraining.
func (mr *MockTrainingParticipantRepositoryMockRecorder) ListByTraining(ctx, trainingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTraining", reflect.TypeOf((*MockTrainingParticipantRepository)(nil).ListByTraining), ctx, trainingID)
}
