// Code generated by MockGen. DO NOT EDIT.
// Source: runclub/internal/domain/repository (interfaces: JointRunRepository,JointRunParticipantRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_jointrun.go -package=mocks runclub/internal/domain/repository JointRunRepository,JointRunParticipantRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entity "runclub/internal/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockJointRunRepository is a mock of JointRunRepository interface.
type MockJointRunRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJointRunRepositoryMockRecorder
	isgomock struct{}
}

// MockJointRunRepositoryMockRecorder is the mock recorder for MockJointRunRepository.
type MockJointRunRepositoryMockRecorder struct {
	mock *MockJointRunRepository
}

// NewMockJointRunRepository creates a new mock instance.
func NewMockJointRunRepository(ctrl *gomock.Controller) *MockJointRunRepository {
	mock := &MockJointRunRepository{ctrl: ctrl}
	mock.recorder = &MockJointRunRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJointRunRepository) EXPECT() *MockJointRunRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockJointRunRepository) Create(ctx context.Context, run *entity.JointRun) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, run)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockJointRunRepositoryMockRecorder) Create(ctx, run any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockJointRunRepository)(nil).Create), ctx, run)
}

// Delete mocks base method.
func (m *MockJointRunRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockJointRunRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockJointRunRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockJointRunRepository) GetByID(ctx context.Context, id int64) (*entity.JointRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.JointRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockJointRunRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockJointRunRepository)(nil).GetByID), ctx, id)
}

// ListByClub mocks base method.
func (m *MockJointRunRepository) ListByClub(ctx context.Context, clubID int64) ([]entity.JointRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByClub", ctx, clubID)
	ret0, _ := ret[0].([]entity.JointRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByClub indicates an expected call of ListByClub.
func (mr *MockJointRunRepositoryMockRecorder) ListByClub(ctx, clubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByClub", reflect.TypeOf((*MockJointRunRepository)(nil).ListByClub), ctx, clubID)
}

// Update mocks base method.
func (m *MockJointRunRepository) Update(ctx context.Context, run *entity.JointRun) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, run)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockJointRunRepositoryMockRecorder) Update(ctx, run any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockJointRunRepository)(nil).Update), ctx, run)
}

// MockJointRunParticipantRepository is a mock of JointRunParticipantRepository interface.
type MockJointRunParticipantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJointRunParticipantRepositoryMockRecorder
	isgomock struct{}
}

// MockJointRunParticipantRepositoryMockRecorder is the mock recorder for MockJointRunParticipantRepository.
type MockJointRunParticipantRepositoryMockRecorder struct {
	mock *MockJointRunParticipantRepository
}

// NewMockJointRunParticipantRepository creates a new mock instance.
func NewMockJointRunParticipantRepository(ctrl *gomock.Controller) *MockJointRunParticipantRepository {
	mock := &MockJointRunParticipantRepository{ctrl: ctrl}
	mock.recorder = &MockJointRunParticipantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJointRunParticipantRepository) EXPECT() *MockJointRunParticipantRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockJointRunParticipantRepository) Create(ctx context.Context, p *entity.JointRunParticipant) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockJointRunParticipantRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockJointRunParticipantRepository)(nil).Create), ctx, p)
}

// Delete mocks base method.
func (m *MockJointRunParticipantRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockJointRunParticipantRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockJointRunParticipantRepository)(nil).Delete), ctx, id)
}

// GetByRunAndMember mocks base method.
func (m *MockJointRunParticipantRepository) GetByRunAndMember(ctx context.Context, runID, memberID int64) (*entity.JointRunParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRunAndMember", ctx, runID, memberID)
	ret0, _ := ret[0].(*entity.JointRunParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRunAndMember indicates an expected call of GetByRunAndMember.
func (mr *MockJointRunParticipantRepositoryMockRecorder) GetByRunAndMember(ctx, runID, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRunAndMember", reflect.TypeOf((*MockJointRunParticipantRepository)(nil).GetByRunAndMember), ctx, runID, memberID)
}

// ListByRun mocks base method.
func (m *MockJointRunParticipantRepository) ListByRun(ctx context.Context, runID int64) ([]entity.JointRunParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByRun", ctx, runID)
	ret0, _ := ret[0].([]entity.JointRunParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByRun indicates an expected call of ListByRun.
func (mr *MockJointRunParticipantRepositoryMockRecorder) ListByRun(ctx, runID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByRun", reflect.TypeOf((*MockJointRunParticipantRepository)(nil).ListByRun), ctx, runID)
}
