// Code generated by MockGen. DO NOT EDIT.
// Source: runclub/internal/domain/repository (interfaces: CustomFieldRepository,CustomFieldValueRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_customfield.go -package=mocks runclub/internal/domain/repository CustomFieldRepository,CustomFieldValueRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entity "runclub/internal/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockCustomFieldRepository is a mock of CustomFieldRepository interface.
type MockCustomFieldRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCustomFieldRepositoryMockRecorder
	isgomock struct{}
}

// MockCustomFieldRepositoryMockRecorder is the mock recorder for MockCustomFieldRepository.
type MockCustomFieldRepositoryMockRecorder struct {
	mock *MockCustomFieldRepository
}

// NewMockCustomFieldRepository creates a new mock instance.
func NewMockCustomFieldRepository(ctrl *gomock.Controller) *MockCustomFieldRepository {
	mock := &MockCustomFieldRepository{ctrl: ctrl}
	mock.recorder = &MockCustomFieldRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomFieldRepository) EXPECT() *MockCustomFieldRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCustomFieldRepository) Create(ctx context.Context, cf *entity.CustomField) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, cf)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCustomFieldRepositoryMockRecorder) Create(ctx, cf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCustomFieldRepository)(nil).Create), ctx, cf)
}

// Delete mocks base method.
func (m *MockCustomFieldRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCustomFieldRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCustomFieldRepository)(nil).Delete), ctx, id)
}

// ListByClub mocks base method.
func (m *MockCustomFieldRepository) ListByClub(ctx context.Context, clubID int64) ([]entity.CustomField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByClub", ctx, clubID)
	ret0, _ := ret[0].([]entity.CustomField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByClub indicates an expected call of ListByClub.
func (mr *MockCustomFieldRepositoryMockRecorder) ListByClub(ctx, clubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByClub", reflect.TypeOf((*MockCustomFieldRepository)(nil).ListByClub), ctx, clubID)
}

// Update mocks base method.
func (m *MockCustomFieldRepository) Update(ctx context.Context, cf *entity.CustomField) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, cf)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCustomFieldRepositoryMockRecorder) Update(ctx, cf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCustomFieldRepository)(nil).Update), ctx, cf)
}

// MockCustomFieldValueRepository is a mock of CustomFieldValueRepository interface.
type MockCustomFieldValueRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCustomFieldValueRepositoryMockRecorder
	isgomock struct{}
}

// MockCustomFieldValueRepositoryMockRecorder is the mock recorder for MockCustomFieldValueRepository.
type MockCustomFieldValueRepositoryMockRecorder struct {
	mock *MockCustomFieldValueRepository
}

// NewMockCustomFieldValueRepository creates a new mock instance.
func NewMockCustomFieldValueRepository(ctrl *gomock.Controller) *MockCustomFieldValueRepository {
	mock := &MockCustomFieldValueRepository{ctrl: ctrl}
	mock.recorder = &MockCustomFieldValueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomFieldValueRepository) EXPECT() *MockCustomFieldValueRepositoryMockRecorder {
	return m.recorder
}

// CreateOrUpdate mocks base method.
func (m *MockCustomFieldValueRepository) CreateOrUpdate(ctx context.Context, cfv *entity.CustomFieldValue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdate", ctx, cfv)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdate indicates an expected call of CreateOrUpdate.
func (mr *MockCustomFieldValueRepositoryMockRecorder) CreateOrUpdate(ctx, cfv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdate", reflect.TypeOf((*MockCustomFieldValueRepository)(nil).CreateOrUpdate), ctx, cfv)
}

// Delete mocks base method.
func (m *MockCustomFieldValueRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCustomFieldValueRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCustomFieldValueRepository)(nil).Delete), ctx, id)
}

// ListByMember mocks base method.
func (m *MockCustomFieldValueRepository) ListByMember(ctx context.Context, memberID int64) ([]entity.CustomFieldValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMember", ctx, memberID)
	ret0, _ := ret[0].([]entity.CustomFieldValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByMember indicates an expected call of ListByMember.
func (mr *MockCustomFieldValueRepositoryMockRecorder) ListByMember(ctx, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMember", reflect.TypeOf((*MockCustomFieldValueRepository)(nil).ListByMember), ctx, memberID)
}
