// Code generated by MockGen. DO NOT EDIT.
// Source: runclub/internal/domain/repository (interfaces: MemberRepository,ClubMemberRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_member.go -package=mocks runclub/internal/domain/repository MemberRepository,ClubMemberRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entity "runclub/internal/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockMemberRepository is a mock of MemberRepository interface.
type MockMemberRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMemberRepositoryMockRecorder
	isgomock struct{}
}

// MockMemberRepositoryMockRecorder is the mock recorder for MockMemberRepository.
type MockMemberRepositoryMockRecorder struct {
	mock *MockMemberRepository
}

// NewMockMemberRepository creates a new mock instance.
func NewMockMemberRepository(ctrl *gomock.Controller) *MockMemberRepository {
	mock := &MockMemberRepository{ctrl: ctrl}
	mock.recorder = &MockMemberRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberRepository) EXPECT() *MockMemberRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMemberRepository) Create(ctx context.Context, member *entity.Member) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, member)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMemberRepositoryMockRecorder) Create(ctx, member any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMemberRepository)(nil).Create), ctx, member)
}

// Delete mocks base method.
func (m *MockMemberRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMemberRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMemberRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockMemberRepository) GetByID(ctx context.Context, id int64) (*entity.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMemberRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMemberRepository)(nil).GetByID), ctx, id)
}

// GetByTelegramID mocks base method.
func (m *MockMemberRepository) GetByTelegramID(ctx context.Context, telegramID int64) (*entity.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTelegramID", ctx, telegramID)
	ret0, _ := ret[0].(*entity.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTelegramID indicates an expected call of GetByTelegramID.
func (mr *MockMemberRepositoryMockRecorder) GetByTelegramID(ctx, telegramID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTelegramID", reflect.TypeOf((*MockMemberRepository)(nil).GetByTelegramID), ctx, telegramID)
}

// ListBirthdayOn mocks base method.
func (m *MockMemberRepository) ListBirthdayOn(ctx context.Context, month, day int) ([]entity.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBirthdayOn", ctx, month, day)
	ret0, _ := ret[0].([]entity.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBirthdayOn indicates an expected call of ListBirthdayOn.
func (mr *MockMemberRepositoryMockRecorder) ListBirthdayOn(ctx, month, day any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBirthdayOn", reflect.TypeOf((*MockMemberRepository)(nil).ListBirthdayOn), ctx, month, day)
}

// ListByClub mocks base method.
func (m *MockMemberRepository) ListByClub(ctx context.Context, clubID int64) ([]entity.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByClub", ctx, clubID)
	ret0, _ := ret[0].([]entity.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByClub indicates an expected call of ListByClub.
func (mr *MockMemberRepositoryMockRecorder) ListByClub(ctx, clubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByClub", reflect.TypeOf((*MockMemberRepository)(nil).ListByClub), ctx, clubID)
}

// ListOrphansOlderThan mocks base method.
func (m *MockMemberRepository) ListOrphansOlderThan(ctx context.Context, days int) ([]entity.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrphansOlderThan", ctx, days)
	ret0, _ := ret[0].([]entity.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrphansOlderThan indicates an expected call of ListOrphansOlderThan.
func (mr *MockMemberRepositoryMockRecorder) ListOrphansOlderThan(ctx, days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrphansOlderThan", reflect.TypeOf((*MockMemberRepository)(nil).ListOrphansOlderThan), ctx, days)
}

// ListTrainersByClub mocks base method.
func (m *MockMemberRepository) ListTrainersByClub(ctx context.Context, clubID int64) ([]entity.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTrainersByClub", ctx, clubID)
	ret0, _ := ret[0].([]entity.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTrainersByClub indicates an expected call of ListTrainersByClub.
func (mr *MockMemberRepositoryMockRecorder) ListTrainersByClub(ctx, clubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTrainersByClub", reflect.TypeOf((*MockMemberRepository)(nil).ListTrainersByClub), ctx, clubID)
}

// Update mocks base method.
func (m *MockMemberRepository) Update(ctx context.Context, member *entity.Member) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMemberRepositoryMockRecorder) Update(ctx, member any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMemberRepository)(nil).Update), ctx, member)
}

// MockClubMemberRepository is a mock of ClubMemberRepository interface.
type MockClubMemberRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClubMemberRepositoryMockRecorder
	isgomock struct{}
}

// MockClubMemberRepositoryMockRecorder is the mock recorder for MockClubMemberRepository.
type MockClubMemberRepositoryMockRecorder struct {
	mock *MockClubMemberRepository
}

// NewMockClubMemberRepository creates a new mock instance.
func NewMockClubMemberRepository(ctrl *gomock.Controller) *MockClubMemberRepository {
	mock := &MockClubMemberRepository{ctrl: ctrl}
	mock.recorder = &MockClubMemberRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClubMemberRepository) EXPECT() *MockClubMemberRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClubMemberRepository) Create(ctx context.Context, cm *entity.ClubMember) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, cm)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClubMemberRepositoryMockRecorder) Create(ctx, cm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClubMemberRepository)(nil).Create), ctx, cm)
}

// Delete mocks base method.
func (m *MockClubMemberRepository) Delete(ctx context.Context, clubID, memberID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, clubID, memberID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClubMemberRepositoryMockRecorder) Delete(ctx, clubID, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClubMemberRepository)(nil).Delete), ctx, clubID, memberID)
}

// GetByClubAndMember mocks base method.
func (m *MockClubMemberRepository) GetByClubAndMember(ctx context.Context, clubID, memberID int64) (*entity.ClubMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByClubAndMember", ctx, clubID, memberID)
	ret0, _ := ret[0].(*entity.ClubMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByClubAndMember indicates an expected call of GetByClubAndMember.
func (mr *MockClubMemberRepositoryMockRecorder) GetByClubAndMember(ctx, clubID, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByClubAndMember", reflect.TypeOf((*MockClubMemberRepository)(nil).GetByClubAndMember), ctx, clubID, memberID)
}

// ListClubsByMember mocks base method.
func (m *MockClubMemberRepository) ListClubsByMember(ctx context.Context, memberID int64) ([]entity.ClubMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClubsByMember", ctx, memberID)
	ret0, _ := ret[0].([]entity.ClubMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClubsByMember indicates an expected call of ListClubsByMember.
func (mr *MockClubMemberRepositoryMockRecorder) ListClubsByMember(ctx, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClubsByMember", reflect.TypeOf((*MockClubMemberRepository)(nil).ListClubsByMember), ctx, memberID)
}

// ListTrainerClubs mocks base method.
func (m *MockClubMemberRepository) ListTrainerClubs(ctx context.Context, memberID int64) ([]entity.ClubMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTrainerClubs", ctx, memberID)
	ret0, _ := ret[0].([]entity.ClubMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTrainerClubs indicates an expected call of ListTrainerClubs.
func (mr *MockClubMemberRepositoryMockRecorder) ListTrainerClubs(ctx, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTrainerClubs", reflect.TypeOf((*MockClubMemberRepository)(nil).ListTrainerClubs), ctx, memberID)
}

// UpdateRole mocks base method.
func (m *MockClubMemberRepository) UpdateRole(ctx context.Context, clubID, memberID int64, role entity.MemberRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", ctx, clubID, memberID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockClubMemberRepositoryMockRecorder) UpdateRole(ctx, clubID, memberID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockClubMemberRepository)(nil).UpdateRole), ctx, clubID, memberID, role)
}
