// Code generated by MockGen. DO NOT EDIT.
// Source: runclub/internal/domain/repository (interfaces: AdminUserRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_adminuser.go -package=mocks runclub/internal/domain/repository AdminUserRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entity "runclub/internal/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockAdminUserRepository is a mock of AdminUserRepository interface.
type MockAdminUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdminUserRepositoryMockRecorder
	isgomock struct{}
}

// MockAdminUserRepositoryMockRecorder is the mock recorder for MockAdminUserRepository.
type MockAdminUserRepositoryMockRecorder struct {
	mock *MockAdminUserRepository
}

// NewMockAdminUserRepository creates a new mock instance.
func NewMockAdminUserRepository(ctrl *gomock.Controller) *MockAdminUserRepository {
	mock := &MockAdminUserRepository{ctrl: ctrl}
	mock.recorder = &MockAdminUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminUserRepository) EXPECT() *MockAdminUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAdminUserRepository) Create(ctx context.Context, user *entity.AdminUser) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAdminUserRepositoryMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAdminUserRepository)(nil).Create), ctx, user)
}

// Delete mocks base method.
func (m *MockAdminUserRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAdminUserRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAdminUserRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockAdminUserRepository) GetByID(ctx context.Context, id int64) (*entity.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAdminUserRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAdminUserRepository)(nil).GetByID), ctx, id)
}

// GetByUsername mocks base method.
func (m *MockAdminUserRepository) GetByUsername(ctx context.Context, username string) (*entity.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", ctx, username)
	ret0, _ := ret[0].(*entity.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockAdminUserRepositoryMockRecorder) GetByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockAdminUserRepository)(nil).GetByUsername), ctx, username)
}

// List mocks base method.
func (m *MockAdminUserRepository) List(ctx context.Context) ([]entity.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAdminUserRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAdminUserRepository)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockAdminUserRepository) Update(ctx context.Context, user *entity.AdminUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAdminUserRepositoryMockRecorder) Update(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAdminUserRepository)(nil).Update), ctx, user)
}
