// Code generated by MockGen. DO NOT EDIT.
// Source: runclub/internal/domain/repository (interfaces: RaceNotificationLogRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_notification.go -package=mocks runclub/internal/domain/repository RaceNotificationLogRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRaceNotificationLogRepository is a mock of RaceNotificationLogRepository interface.
type MockRaceNotificationLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRaceNotificationLogRepositoryMockRecorder
	isgomock struct{}
}

// MockRaceNotificationLogRepositoryMockRecorder is the mock recorder for MockRaceNotificationLogRepository.
type MockRaceNotificationLogRepositoryMockRecorder struct {
	mock *MockRaceNotificationLogRepository
}

// NewMockRaceNotificationLogRepository creates a new mock instance.
func NewMockRaceNotificationLogRepository(ctrl *gomock.Controller) *MockRaceNotificationLogRepository {
	mock := &MockRaceNotificationLogRepository{ctrl: ctrl}
	mock.recorder = &MockRaceNotificationLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRaceNotificationLogRepository) EXPECT() *MockRaceNotificationLogRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRaceNotificationLogRepository) Create(ctx context.Context, clubID, raceID int64, sentDate string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, clubID, raceID, sentDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRaceNotificationLogRepositoryMockRecorder) Create(ctx, clubID, raceID, sentDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRaceNotificationLogRepository)(nil).Create), ctx, clubID, raceID, sentDate)
}

// Exists mocks base method.
func (m *MockRaceNotificationLogRepository) Exists(ctx context.Context, clubID, raceID int64, sentDate string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, clubID, raceID, sentDate)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockRaceNotificationLogRepositoryMockRecorder) Exists(ctx, clubID, raceID, sentDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockRaceNotificationLogRepository)(nil).Exists), ctx, clubID, raceID, sentDate)
}
