// Code generated by MockGen. DO NOT EDIT.
// Source: runclub/internal/domain/repository (interfaces: LocationRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_location.go -package=mocks runclub/internal/domain/repository LocationRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entity "runclub/internal/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockLocationRepository is a mock of LocationRepository interface.
type MockLocationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLocationRepositoryMockRecorder
	isgomock struct{}
}

// MockLocationRepositoryMockRecorder is the mock recorder for MockLocationRepository.
type MockLocationRepositoryMockRecorder struct {
	mock *MockLocationRepository
}

// NewMockLocationRepository creates a new mock instance.
func NewMockLocationRepository(ctrl *gomock.Controller) *MockLocationRepository {
	mock := &MockLocationRepository{ctrl: ctrl}
	mock.recorder = &MockLocationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocationRepository) EXPECT() *MockLocationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLocationRepository) Create(ctx context.Context, location *entity.Location) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, location)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockLocationRepositoryMockRecorder) Create(ctx, location any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLocationRepository)(nil).Create), ctx, location)
}

// Delete mocks base method.
func (m *MockLocationRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLocationRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLocationRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockLocationRepository) GetByID(ctx context.Context, id int64) (*entity.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockLocationRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockLocationRepository)(nil).GetByID), ctx, id)
}

// ListByClub mocks base method.
func (m *MockLocationRepository) ListByClub(ctx context.Context, clubID int64) ([]entity.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByClub", ctx, clubID)
	ret0, _ := ret[0].([]entity.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByClub indicates an expected call of ListByClub.
func (mr *MockLocationRepositoryMockRecorder) ListByClub(ctx, clubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByClub", reflect.TypeOf((*MockLocationRepository)(nil).ListByClub), ctx, clubID)
}

// Update mocks base method.
func (m *MockLocationRepository) Update(ctx context.Context, location *entity.Location) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, location)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLocationRepositoryMockRecorder) Update(ctx, location any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLocationRepository)(nil).Update), ctx, location)
}
