// Code generated by MockGen. DO NOT EDIT.
// Source: runclub/internal/domain/repository (interfaces: AdminUserClubRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_adminuserclub.go -package=mocks runclub/internal/domain/repository AdminUserClubRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAdminUserClubRepository is a mock of AdminUserClubRepository interface.
type MockAdminUserClubRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdminUserClubRepositoryMockRecorder
	isgomock struct{}
}

// MockAdminUserClubRepositoryMockRecorder is the mock recorder for MockAdminUserClubRepository.
type MockAdminUserClubRepositoryMockRecorder struct {
	mock *MockAdminUserClubRepository
}

// NewMockAdminUserClubRepository creates a new mock instance.
func NewMockAdminUserClubRepository(ctrl *gomock.Controller) *MockAdminUserClubRepository {
	mock := &MockAdminUserClubRepository{ctrl: ctrl}
	mock.recorder = &MockAdminUserClubRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminUserClubRepository) EXPECT() *MockAdminUserClubRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockAdminUserClubRepository) Add(ctx context.Context, adminUserID, clubID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, adminUserID, clubID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockAdminUserClubRepositoryMockRecorder) Add(ctx, adminUserID, clubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockAdminUserClubRepository)(nil).Add), ctx, adminUserID, clubID)
}

// ListByAdminUser mocks base method.
func (m *MockAdminUserClubRepository) ListByAdminUser(ctx context.Context, adminUserID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAdminUser", ctx, adminUserID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAdminUser indicates an expected call of ListByAdminUser.
func (mr *MockAdminUserClubRepositoryMockRecorder) ListByAdminUser(ctx, adminUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAdminUser", reflect.TypeOf((*MockAdminUserClubRepository)(nil).ListByAdminUser), ctx, adminUserID)
}

// ListByClub mocks base method.
func (m *MockAdminUserClubRepository) ListByClub(ctx context.Context, clubID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByClub", ctx, clubID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByClub indicates an expected call of ListByClub.
func (mr *MockAdminUserClubRepositoryMockRecorder) ListByClub(ctx, clubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByClub", reflect.TypeOf((*MockAdminUserClubRepository)(nil).ListByClub), ctx, clubID)
}

// Remove mocks base method.
func (m *MockAdminUserClubRepository) Remove(ctx context.Context, adminUserID, clubID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, adminUserID, clubID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockAdminUserClubRepositoryMockRecorder) Remove(ctx, adminUserID, clubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockAdminUserClubRepository)(nil).Remove), ctx, adminUserID, clubID)
}
